export default [
  {
    make: 'Porsche',
    model: '911',
    year: 2021,
    price: 99999,
    engineType: 'Gasoline',
    engineDisplacement: '3.0 L',
    power: 450,
    transmission: 'Automatic',
    mileage: 12000,
    imageUrl: 'https://example.com/image1.jpg',
    interiorFeatures: 'Leather seats, premium sound system',
    safetyFeatures: 'Airbags, ABS, stability control',
    serviceHistory: 'Full service history available',
    financingOptions: 'Financing available through dealership',
    description:
      'The Porsche 911 is a classic sports car with an iconic design, powerful performance, and luxurious interior.',
  },
  {
    make: 'Aston',
    model: 'DB12',
    year: 2022,
    price: 75000,
    engineType: 'Diesel',
    engineDisplacement: '2.0 L',
    power: 300,
    transmission: 'Automatic',
    mileage: 8000,
    imageUrl: 'https://example.com/image2.jpg',
    interiorFeatures: 'Leather seats, digital cockpit',
    safetyFeatures: 'Airbags, lane assist, parking sensors',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Audi A6 combines elegance and technology with a powerful engine and advanced safety features.',
  },
  {
    make: 'Mercedes',
    model: 'C-Class',
    year: 2023,
    price: 60000,
    engineType: 'Gasoline',
    engineDisplacement: '1.5 L',
    power: 250,
    transmission: 'Manual',
    mileage: 5000,
    imageUrl: 'https://example.com/image3.jpg',
    interiorFeatures: 'Leather seats, premium audio system',
    safetyFeatures: 'ABS, ESP, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Mercedes C-Class offers a refined driving experience with top-notch comfort and cutting-edge technology.',
  },
  {
    make: 'BMW',
    model: 'X5',
    year: 2023,
    price: 85000,
    engineType: 'Gasoline',
    engineDisplacement: '3.0 L',
    power: 335,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image4.jpg',
    interiorFeatures: 'Leather upholstery, navigation system',
    safetyFeatures: 'Forward collision warning, blind-spot monitoring',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The BMW X5 is a versatile luxury SUV with robust performance and spacious interior for families.',
  },
  {
    make: 'Ford',
    model: 'Mustang',
    year: 2022,
    price: 55000,
    engineType: 'Gasoline',
    engineDisplacement: '5.0 L',
    power: 450,
    transmission: 'Automatic',
    mileage: 3000,
    imageUrl: 'https://example.com/image5.jpg',
    interiorFeatures: 'Leather seats, premium sound system',
    safetyFeatures: 'Airbags, rearview camera',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Ford Mustang is a symbol of American muscle, offering thrilling performance and modern technology.',
  },
  {
    make: 'Tesla',
    model: 'Model S',
    year: 2023,
    price: 95000,
    engineType: 'Electric',
    engineDisplacement: 'N/A',
    power: 670,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image6.jpg',
    interiorFeatures: 'Minimalist interior, large touchscreen',
    safetyFeatures: 'Autopilot, emergency braking',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Tesla Model S is a high-performance electric sedan with impressive range and cutting-edge technology.',
  },
  {
    make: 'Chevrolet',
    model: 'Corvette',
    year: 2022,
    price: 80000,
    engineType: 'Gasoline',
    engineDisplacement: '6.2 L',
    power: 495,
    transmission: 'Automatic',
    mileage: 1500,
    imageUrl: 'https://example.com/image7.jpg',
    interiorFeatures: 'Leather seats, heads-up display',
    safetyFeatures: 'Stability control, rearview camera',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Chevrolet Corvette is a legendary sports car known for its striking design and blistering performance.',
  },
  {
    make: 'Nissan',
    model: 'Altima',
    year: 2023,
    price: 30000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 188,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image8.jpg',
    interiorFeatures: 'Cloth seats, advanced infotainment system',
    safetyFeatures: 'Automatic emergency braking, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Nissan Altima is a stylish sedan that balances performance and efficiency with modern tech features.',
  },
  {
    make: 'Volkswagen',
    model: 'Golf',
    year: 2022,
    price: 35000,
    engineType: 'Gasoline',
    engineDisplacement: '1.4 L',
    power: 147,
    transmission: 'Automatic',
    mileage: 2000,
    imageUrl: 'https://example.com/image9.jpg',
    interiorFeatures: 'Leatherette seats, touch screen navigation',
    safetyFeatures: 'Adaptive cruise control, rearview camera',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Volkswagen Golf is a compact hatchback that offers practicality, performance, and a premium feel.',
  },
  {
    make: 'Subaru',
    model: 'Outback',
    year: 2023,
    price: 35000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 182,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image10.jpg',
    interiorFeatures: 'Water-resistant upholstery, large cargo space',
    safetyFeatures: 'EyeSight driver assist technology, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Subaru Outback is a versatile crossover designed for adventure, with ample cargo space and safety features.',
  },
  {
    make: 'Hyundai',
    model: 'Elantra',
    year: 2023,
    price: 25000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 147,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image11.jpg',
    interiorFeatures: 'Cloth seats, user-friendly interface',
    safetyFeatures: 'Lane keeping assist, blind-spot monitoring',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Hyundai Elantra is a compact sedan that offers a stylish design and a suite of safety technologies.',
  },
  {
    make: 'Kia',
    model: 'K5',
    year: 2023,
    price: 27000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 195,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image12.jpg',
    interiorFeatures: 'Leatherette seats, 10.25-inch touchscreen',
    safetyFeatures: 'Smart cruise control, forward collision warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Kia K5 is a sporty sedan with a bold design and advanced technology features for modern drivers.',
  },
  {
    make: 'Mazda',
    model: 'CX-5',
    year: 2022,
    price: 32000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 187,
    transmission: 'Automatic',
    mileage: 12000,
    imageUrl: 'https://example.com/image13.jpg',
    interiorFeatures: 'Leather seats, Bose sound system',
    safetyFeatures: 'Rear cross traffic alert, lane departure warning',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Mazda CX-5 is a stylish compact SUV that combines sporty handling with a premium interior.',
  },
  {
    make: 'Lexus',
    model: 'RX 350',
    year: 2023,
    price: 47000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 295,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image14.jpg',
    interiorFeatures: 'Leather upholstery, premium audio',
    safetyFeatures: 'Adaptive cruise control, pre-collision system',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Lexus RX 350 is a luxury SUV that delivers comfort, performance, and cutting-edge technology.',
  },
  {
    make: 'Chrysler',
    model: 'Pacifica',
    year: 2022,
    price: 40000,
    engineType: 'Gasoline',
    engineDisplacement: '3.6 L',
    power: 287,
    transmission: 'Automatic',
    mileage: 10000,
    imageUrl: 'https://example.com/image15.jpg',
    interiorFeatures: 'Stow ’n Go seating, touchscreen',
    safetyFeatures: 'Rearview camera, blind-spot monitoring',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Chrysler Pacifica is a family-friendly minivan that offers versatility and comfort for every journey.',
  },
  {
    make: 'Dodge',
    model: 'Durango',
    year: 2023,
    price: 49000,
    engineType: 'Gasoline',
    engineDisplacement: '3.6 L',
    power: 295,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image16.jpg',
    interiorFeatures: 'Leather seats, infotainment system',
    safetyFeatures: 'Adaptive cruise control, advanced airbag system',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Dodge Durango is a powerful SUV with a spacious interior and advanced technology for families.',
  },
  {
    make: 'Jaguar',
    model: 'F-PACE',
    year: 2022,
    price: 70000,
    engineType: 'Diesel',
    engineDisplacement: '2.0 L',
    power: 180,
    transmission: 'Automatic',
    mileage: 8000,
    imageUrl: 'https://example.com/image17.jpg',
    interiorFeatures: 'Leather upholstery, panoramic roof',
    safetyFeatures: 'Emergency braking, lane keep assist',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Jaguar F-PACE combines performance and luxury with a spacious interior and advanced features.',
  },
  {
    make: 'Volvo',
    model: 'XC90',
    year: 2023,
    price: 75000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 250,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image18.jpg',
    interiorFeatures: 'Leather seats, advanced navigation',
    safetyFeatures: 'Pilot assist, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Volvo XC90 is a luxury SUV known for its safety, performance, and premium interior finishes.',
  },
  {
    make: 'Land Rover',
    model: 'Discovery',
    year: 2023,
    price: 85000,
    engineType: 'Gasoline',
    engineDisplacement: '3.0 L',
    power: 355,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image19.jpg',
    interiorFeatures: 'Luxurious leather, heated seats',
    safetyFeatures: '360-degree camera, adaptive cruise control',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Land Rover Discovery offers off-road capabilities and luxury, perfect for adventurous families.',
  },
  {
    make: 'Fiat',
    model: '500',
    year: 2023,
    price: 20000,
    engineType: 'Gasoline',
    engineDisplacement: '1.4 L',
    power: 135,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image20.jpg',
    interiorFeatures: 'Stylish interior, compact size',
    safetyFeatures: 'Multiple airbags, rear parking sensors',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Fiat 500 is a small car with a big personality, ideal for city driving and urban adventures.',
  },
  {
    make: 'Acura',
    model: 'RDX',
    year: 2022,
    price: 43000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 272,
    transmission: 'Automatic',
    mileage: 5000,
    imageUrl: 'https://example.com/image21.jpg',
    interiorFeatures: 'Premium audio, spacious cabin',
    safetyFeatures: 'Collision mitigation braking, road departure mitigation',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Acura RDX is a luxury SUV that combines performance, comfort, and technology for an enjoyable ride.',
  },
  {
    make: 'Infiniti',
    model: 'QX60',
    year: 2023,
    price: 58000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 295,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image22.jpg',
    interiorFeatures: 'Leather seats, spacious interior',
    safetyFeatures:
      'Predictive forward collision warning, intelligent cruise control',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Infiniti QX60 is a family-friendly luxury SUV with advanced safety features and a premium interior.',
  },
  {
    make: 'Mitsubishi',
    model: 'Outlander',
    year: 2023,
    price: 29000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 181,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image23.jpg',
    interiorFeatures: 'Comfortable seating, touchscreen interface',
    safetyFeatures: 'Forward collision mitigation, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Mitsubishi Outlander is a versatile SUV that provides comfort and space for families and adventurers alike.',
  },
  {
    make: 'Porsche',
    model: 'Macan',
    year: 2022,
    price: 60000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 265,
    transmission: 'Automatic',
    mileage: 4000,
    imageUrl: 'https://example.com/image24.jpg',
    interiorFeatures: 'Leather seats, high-end audio system',
    safetyFeatures: 'Adaptive cruise control, multiple airbags',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Porsche Macan blends sporty performance with luxury and comfort, making it a desirable compact SUV.',
  },
  {
    make: 'Genesis',
    model: 'GV80',
    year: 2023,
    price: 75000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 375,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image25.jpg',
    interiorFeatures: 'Luxury materials, spacious seating',
    safetyFeatures: 'Smart cruise control, forward collision warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Genesis GV80 is a luxury SUV that offers a refined driving experience with top-tier safety features.',
  },
  {
    make: 'Chevrolet',
    model: 'Tahoe',
    year: 2022,
    price: 60000,
    engineType: 'Gasoline',
    engineDisplacement: '5.3 L',
    power: 355,
    transmission: 'Automatic',
    mileage: 7000,
    imageUrl: 'https://example.com/image26.jpg',
    interiorFeatures: 'Spacious cabin, advanced infotainment',
    safetyFeatures: 'Blind-spot monitoring, adaptive cruise control',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Chevrolet Tahoe is a full-size SUV with plenty of space for passengers and cargo, ideal for family adventures.',
  },
  {
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    price: 32000,
    engineType: 'Gasoline',
    engineDisplacement: '1.5 L',
    power: 190,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image27.jpg',
    interiorFeatures: 'Comfortable seats, large cargo space',
    safetyFeatures: 'Collision mitigation braking, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Honda CR-V is a popular compact SUV known for its reliability, spacious interior, and advanced safety features.',
  },
  {
    make: 'Toyota',
    model: 'RAV4',
    year: 2023,
    price: 35000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 203,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image28.jpg',
    interiorFeatures: 'Comfortable seating, touchscreen interface',
    safetyFeatures: 'Toyota Safety Sense, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Toyota RAV4 is a versatile SUV that combines performance and efficiency, perfect for everyday driving.',
  },
  {
    make: 'Nissan',
    model: 'Rogue',
    year: 2022,
    price: 29000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 181,
    transmission: 'CVT',
    mileage: 5000,
    imageUrl: 'https://example.com/image29.jpg',
    interiorFeatures: 'Spacious interior, modern infotainment',
    safetyFeatures: 'ProPILOT Assist, rear cross traffic alert',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Nissan Rogue is a compact SUV with a stylish design, advanced technology, and plenty of room for passengers and cargo.',
  },
  {
    make: 'Kia',
    model: 'Soul',
    year: 2023,
    price: 22000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 147,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image30.jpg',
    interiorFeatures: 'Unique design, spacious interior',
    safetyFeatures: 'Forward collision warning, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Kia Soul is a compact crossover that offers a distinctive design, roomy interior, and a fun driving experience.',
  },
  {
    make: 'Subaru',
    model: 'Forester',
    year: 2023,
    price: 35000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 182,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image31.jpg',
    interiorFeatures: 'Spacious interior, user-friendly tech',
    safetyFeatures: 'EyeSight driver assist technology, rearview camera',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Subaru Forester is a compact SUV designed for adventure, offering all-wheel drive and a roomy interior.',
  },
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    year: 2022,
    price: 33000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 184,
    transmission: 'Automatic',
    mileage: 6000,
    imageUrl: 'https://example.com/image32.jpg',
    interiorFeatures: 'Spacious interior, advanced tech',
    safetyFeatures: 'Blind-spot monitor, rear traffic alert',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Volkswagen Tiguan is a compact SUV that offers versatility, comfort, and advanced safety features.',
  },
  {
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 28000,
    engineType: 'Gasoline',
    engineDisplacement: '1.5 L',
    power: 192,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image33.jpg',
    interiorFeatures: 'Spacious seating, advanced infotainment',
    safetyFeatures: 'Honda Sensing suite, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Honda Accord is a midsize sedan that offers a comfortable ride, spacious interior, and a reputation for reliability.',
  },
  {
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    price: 30000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 203,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image34.jpg',
    interiorFeatures: 'Comfortable seats, touchscreen interface',
    safetyFeatures: 'Toyota Safety Sense, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Toyota Camry is a popular midsize sedan known for its reliability, comfort, and fuel efficiency.',
  },
  {
    make: 'Ford',
    model: 'Explorer',
    year: 2023,
    price: 45000,
    engineType: 'Gasoline',
    engineDisplacement: '2.3 L',
    power: 300,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image35.jpg',
    interiorFeatures: 'Spacious seating, advanced technology',
    safetyFeatures: 'Blind-spot monitoring, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Ford Explorer is a midsize SUV that offers plenty of space for families and advanced safety features.',
  },
  {
    make: 'Chevrolet',
    model: 'Silverado 1500',
    year: 2022,
    price: 52000,
    engineType: 'Gasoline',
    engineDisplacement: '5.3 L',
    power: 355,
    transmission: 'Automatic',
    mileage: 8000,
    imageUrl: 'https://example.com/image36.jpg',
    interiorFeatures: 'Spacious interior, advanced infotainment',
    safetyFeatures: 'Lane change alert, rear parking sensors',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Chevrolet Silverado 1500 is a rugged and capable pickup truck that provides both power and comfort.',
  },
  {
    make: 'Ram',
    model: '1500',
    year: 2023,
    price: 58000,
    engineType: 'Gasoline',
    engineDisplacement: '5.7 L',
    power: 395,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image37.jpg',
    interiorFeatures: 'Luxury materials, spacious cabin',
    safetyFeatures: 'Adaptive cruise control, blind-spot monitoring',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Ram 1500 is a full-size pickup that combines capability with a luxurious ride and advanced technology.',
  },
  {
    make: 'GMC',
    model: 'Sierra 1500',
    year: 2022,
    price: 61000,
    engineType: 'Gasoline',
    engineDisplacement: '5.3 L',
    power: 355,
    transmission: 'Automatic',
    mileage: 5000,
    imageUrl: 'https://example.com/image38.jpg',
    interiorFeatures: 'Premium sound system, spacious cabin',
    safetyFeatures: 'Lane keep assist, rear cross traffic alert',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The GMC Sierra 1500 is a powerful and refined pickup truck designed for both work and play.',
  },
  {
    make: 'Toyota',
    model: 'Tundra',
    year: 2023,
    price: 70000,
    engineType: 'Gasoline',
    engineDisplacement: '5.7 L',
    power: 381,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image39.jpg',
    interiorFeatures: 'Spacious interior, advanced tech features',
    safetyFeatures: 'Adaptive cruise control, pre-collision system',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Toyota Tundra is a full-size pickup truck known for its durability, performance, and advanced safety features.',
  },
  {
    make: 'Honda',
    model: 'Ridgeline',
    year: 2023,
    price: 37000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 280,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image40.jpg',
    interiorFeatures: 'Spacious seating, innovative truck bed',
    safetyFeatures: 'Collision mitigation braking, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Honda Ridgeline is a versatile pickup truck that offers a car-like ride with the capability of a truck.',
  },
  {
    make: 'Nissan',
    model: 'Titan',
    year: 2023,
    price: 62000,
    engineType: 'Gasoline',
    engineDisplacement: '5.6 L',
    power: 400,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image41.jpg',
    interiorFeatures: 'Spacious interior, high-quality materials',
    safetyFeatures: 'Blind-spot monitoring, rear cross traffic alert',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Nissan Titan is a full-size pickup truck that offers a powerful engine and a well-appointed interior.',
  },
  {
    make: 'Ford',
    model: 'F-150',
    year: 2022,
    price: 65000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 400,
    transmission: 'Automatic',
    mileage: 6000,
    imageUrl: 'https://example.com/image42.jpg',
    interiorFeatures: 'Spacious cabin, advanced technology',
    safetyFeatures: 'Adaptive cruise control, pre-collision assist',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Ford F-150 is a best-selling pickup truck known for its capability, technology, and comfort.',
  },
  {
    make: 'Chevrolet',
    model: 'Colorado',
    year: 2023,
    price: 32000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 200,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image43.jpg',
    interiorFeatures: 'Comfortable seating, user-friendly tech',
    safetyFeatures: 'Rear vision camera, stability control',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Chevrolet Colorado is a midsize pickup that offers versatility, performance, and modern features.',
  },
  {
    make: 'Hyundai',
    model: 'Santa Cruz',
    year: 2023,
    price: 39000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 281,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image44.jpg',
    interiorFeatures: 'Spacious cabin, innovative storage',
    safetyFeatures: 'Forward collision-avoidance assist, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Hyundai Santa Cruz is a unique crossover pickup truck that blends the benefits of an SUV and a pickup.',
  },
  {
    make: 'Ram',
    model: '2500',
    year: 2023,
    price: 75000,
    engineType: 'Diesel',
    engineDisplacement: '6.7 L',
    power: 370,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image45.jpg',
    interiorFeatures: 'Luxury materials, spacious interior',
    safetyFeatures: 'Blind-spot monitoring, adaptive cruise control',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Ram 2500 is a heavy-duty truck built for towing and hauling, offering both power and luxury.',
  },
  {
    make: 'Ford',
    model: 'Maverick',
    year: 2023,
    price: 27000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 191,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image46.jpg',
    interiorFeatures: 'Comfortable seating, modern tech',
    safetyFeatures: 'Pre-collision assist, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Ford Maverick is a compact pickup truck that offers versatility and efficiency for urban lifestyles.',
  },
  {
    make: 'Honda',
    model: 'Pilot',
    year: 2023,
    price: 43000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 280,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image47.jpg',
    interiorFeatures: 'Spacious seating, user-friendly interface',
    safetyFeatures: 'Collision mitigation braking, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Honda Pilot is a midsize SUV that offers ample space and advanced safety features for families.',
  },
  {
    make: 'Kia',
    model: 'Telluride',
    year: 2023,
    price: 50000,
    engineType: 'Gasoline',
    engineDisplacement: '3.8 L',
    power: 291,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image48.jpg',
    interiorFeatures: 'Luxury seating, advanced infotainment',
    safetyFeatures: 'Blind-spot monitoring, forward collision warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Kia Telluride is a family-friendly SUV that combines style, space, and modern technology.',
  },
  {
    make: 'Mazda',
    model: 'CX-5',
    year: 2022,
    price: 35000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 187,
    transmission: 'Automatic',
    mileage: 7000,
    imageUrl: 'https://example.com/image49.jpg',
    interiorFeatures: 'Premium materials, comfortable seats',
    safetyFeatures: 'Smart brake support, lane departure warning',
    serviceHistory: 'No previous service history',
    financingOptions: 'Options available through dealership',
    description:
      'The Mazda CX-5 is a compact SUV that offers a sporty drive, upscale interior, and advanced safety features.',
  },
  {
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    price: 32000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 187,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image50.jpg',
    interiorFeatures: 'Spacious interior, modern tech',
    safetyFeatures: 'Forward collision-avoidance assist, lane keeping assist',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Hyundai Tucson is a compact SUV known for its stylish design, spacious cabin, and advanced safety features.',
  },
  {
    make: 'Kia',
    model: 'Seltos',
    year: 2023,
    price: 27000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 146,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image51.jpg',
    interiorFeatures: 'Modern interior, user-friendly tech',
    safetyFeatures: 'Blind-spot monitoring, rear cross traffic alert',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Kia Seltos is a subcompact SUV that offers a combination of style, technology, and versatility.',
  },
  {
    make: 'Toyota',
    model: 'Highlander',
    year: 2023,
    price: 46000,
    engineType: 'Gasoline',
    engineDisplacement: '3.5 L',
    power: 295,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image52.jpg',
    interiorFeatures: 'Spacious seating, modern infotainment',
    safetyFeatures: 'Toyota Safety Sense, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Installment options available',
    description:
      'The Toyota Highlander is a midsize SUV that offers a spacious interior, advanced technology, and impressive safety features.',
  },
  {
    make: 'Subaru',
    model: 'Outback',
    year: 2023,
    price: 35000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 182,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image53.jpg',
    interiorFeatures: 'Spacious interior, user-friendly tech',
    safetyFeatures: 'EyeSight driver assist technology, rearview camera',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Subaru Outback is a versatile wagon that combines car-like handling with SUV capability.',
  },
  {
    make: 'Mazda',
    model: 'CX-30',
    year: 2023,
    price: 30000,
    engineType: 'Gasoline',
    engineDisplacement: '2.5 L',
    power: 186,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image54.jpg',
    interiorFeatures: 'Stylish design, premium materials',
    safetyFeatures: 'Smart brake support, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Mazda CX-30 is a subcompact SUV that offers a sporty drive and a well-appointed interior.',
  },
  {
    make: 'Nissan',
    model: 'Kicks',
    year: 2023,
    price: 23000,
    engineType: 'Gasoline',
    engineDisplacement: '1.6 L',
    power: 122,
    transmission: 'CVT',
    mileage: 0,
    imageUrl: 'https://example.com/image55.jpg',
    interiorFeatures: 'Spacious interior, modern tech',
    safetyFeatures: 'Automatic emergency braking, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Nissan Kicks is a subcompact SUV that offers great value, practicality, and style.',
  },
  {
    make: 'Chrysler',
    model: 'Pacifica',
    year: 2023,
    price: 49000,
    engineType: 'Gasoline',
    engineDisplacement: '3.6 L',
    power: 287,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image56.jpg',
    interiorFeatures: 'Spacious interior, family-friendly features',
    safetyFeatures: 'Adaptive cruise control, blind-spot monitoring',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Chrysler Pacifica is a versatile minivan that offers ample space and advanced technology for families.',
  },
  {
    make: 'Mercedes-Benz',
    model: 'GLE',
    year: 2023,
    price: 68000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 255,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image57.jpg',
    interiorFeatures: 'Luxury interior, advanced tech',
    safetyFeatures: 'Active brake assist, blind-spot monitoring',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Mercedes-Benz GLE is a luxury SUV that offers exceptional comfort, advanced technology, and performance.',
  },
  {
    make: 'BMW',
    model: 'X5',
    year: 2023,
    price: 70000,
    engineType: 'Gasoline',
    engineDisplacement: '3.0 L',
    power: 335,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image58.jpg',
    interiorFeatures: 'Luxurious interior, advanced infotainment',
    safetyFeatures: 'Active driving assistant, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The BMW X5 is a luxury midsize SUV that combines performance, comfort, and advanced technology.',
  },
  {
    make: 'Porsche',
    model: 'Macan',
    year: 2023,
    price: 90000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 265,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image59.jpg',
    interiorFeatures: 'Premium materials, sporty design',
    safetyFeatures: 'Porsche active safety system, adaptive cruise control',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Porsche Macan is a compact luxury SUV that offers a thrilling driving experience and luxurious amenities.',
  },
  {
    make: 'Tesla',
    model: 'Model X',
    year: 2023,
    price: 120000,
    engineType: 'Electric',
    engineDisplacement: 'N/A',
    power: 1020,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image60.jpg',
    interiorFeatures: 'Spacious interior, high-tech features',
    safetyFeatures: 'Autopilot, multiple airbags',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Tesla Model X is a luxury electric SUV that offers impressive range, performance, and advanced technology.',
  },
  {
    make: 'Volvo',
    model: 'XC90',
    year: 2023,
    price: 75000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 250,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image61.jpg',
    interiorFeatures: 'Luxurious interior, advanced safety features',
    safetyFeatures: 'Pilot Assist, collision avoidance',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Volvo XC90 is a luxury midsize SUV that prioritizes safety, comfort, and advanced technology.',
  },
  {
    make: 'Audi',
    model: 'Q7',
    year: 2023,
    price: 85000,
    engineType: 'Gasoline',
    engineDisplacement: '3.0 L',
    power: 335,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image62.jpg',
    interiorFeatures: 'Spacious interior, premium sound system',
    safetyFeatures: 'Adaptive cruise control, lane departure warning',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Audi Q7 is a luxury SUV that combines performance, comfort, and advanced technology for a superior driving experience.',
  },
  {
    make: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2023,
    price: 95000,
    engineType: 'Gasoline',
    engineDisplacement: '3.0 L',
    power: 355,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image63.jpg',
    interiorFeatures: 'Luxurious interior, off-road capability',
    safetyFeatures: '360-degree camera, adaptive cruise control',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Land Rover Range Rover Sport is a luxury SUV that offers performance and off-road capabilities without compromising comfort.',
  },
  {
    make: 'Jaguar',
    model: 'F-PACE',
    year: 2023,
    price: 80000,
    engineType: 'Gasoline',
    engineDisplacement: '2.0 L',
    power: 246,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image64.jpg',
    interiorFeatures: 'Spacious interior, premium materials',
    safetyFeatures: 'Adaptive cruise control, emergency braking',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Jaguar F-PACE is a luxury SUV that combines performance, style, and practicality for the modern driver.',
  },
  {
    make: 'Chrysler',
    model: 'Voyager',
    year: 2023,
    price: 42000,
    engineType: 'Gasoline',
    engineDisplacement: '3.6 L',
    power: 287,
    transmission: 'Automatic',
    mileage: 0,
    imageUrl: 'https://example.com/image65.jpg',
    interiorFeatures: 'Family-friendly features, spacious interior',
    safetyFeatures: 'Adaptive cruise control, blind-spot monitoring',
    serviceHistory: 'Not applicable (new vehicle)',
    financingOptions: 'Financing options available',
    description:
      'The Chrysler Voyager is a family-friendly minivan that offers comfort, space, and advanced technology.',
  },
];
